package br.com.abc.javacore.exception.error.test;
/*EXCEPTION SAO CLASSES, TODAS AS EXCEPTIONS SAO FILHAS DA CLASSE 'Throwable'.
 * QUANDO OCORRE UMA EXCEPTION, DIZEMOS QUE O METODO LANCOU UMA EXCEPION.
 * A CLASSE ERROR E UM POUCO DIFERENTE.
 * ERROR E UMA EXCEPTION MAS TECNICAMENTE NAO, POIS NAO E FILHA DA CLASSE Throwable.
 * CHECKED(Chegado) = SAO EXCEPTIONS QUE NECESSITAM DA CRIACAO DE UM TRATAMENTO.NORMALMENTE ERROS FORA DO CONTROLE DO PROGRAMADOR.
 * UNCHECKED(Nao checado) = SAO EXCEPTIONS QUE NAO NECESSITAM DA CRIACAO DE UM TRATAMENTO.NORMALMENTE ERROS DE LOGICA.
 * RunTimeException . TODOS OS ERROS CLASSIFICADOS APARTIR DE RunTimeException SAO CLASSIFIADOS COMO UNCHECKED.
  
 */

public class ErrorTest {
	public static void main(String[] args) {

	}

	public static void stackOverflowError() {
		stackOverflowError();
	}

}
